import {MatIconRegistry} from '@angular/material/icon';
import {DomSanitizer} from '@angular/platform-browser';
import {IconInterface} from '@core/models/icon.model';

const iconsConstant: IconInterface[] = [
	{name: 'logo-icon', path: 'logo-icon.svg'},
	//   {name: 'blue-arrow-icon', path: 'blue-arrow-icon.svg'},
	//   {name: 'vetted-icon', path: 'vetted-icon.svg'},
	//   {name: 'customized-icon', path: 'customized-icon.svg'},
	//   {name: 'transparent-icon', path: 'transparent-icon.svg'},
	//   {name: 'flexible-icon', path: 'flexible-icon.svg'},
	//   {name: 'secure-icon', path: 'secure-icon.svg'},
	//   {name: 'first-icon', path: 'first-icon.svg'},
	//   {name: 'second-icon', path: 'second-icon.svg'},
	//   {name: 'third-icon', path: 'third-icon.svg'},
	//   {name: 'twitter-icon', path: 'twitter-icon.svg'},
	//   {name: 'instagram-icon', path: 'instagram-icon.svg'},
	//   {name: 'facebook-icon', path: 'facebook-icon.svg'},
	//   {name: 'globe-icon', path: 'globe-icon.svg'},
	//   {name: 'grey-arrow-icon', path: 'grey-arrow-icon.svg'},
	{name: 'burger-icon', path: 'burger-icon.svg'},
	{name: 'person-icon', path: 'person-icon.svg'},
	//   {name: 'credit-cards-icon', path: 'credit-cards-icon.svg'},
	//   {name: 'privacy-folder-icon', path: 'privacy-folder-icon.svg'},
	//   {name: 'reviews-icon', path: 'reviews-icon.svg'},
	//   {name: 'service-icon', path: 'service-icon.svg'},
	//   {name: 'settings-icon', path: 'settings-icon.svg'},
	//   {name: 'troubleshooting-icon', path: 'troubleshooting-icon.svg'},
	//   {name: 'dropdown-arrow-icon', path: 'dropdown-arrow-icon.svg'},
	//   {name: 'upload-icon', path: 'upload-icon.svg'},
	//   {name: 'eye-hiding-icon', path: 'eye-hiding-icon.svg'},
	//   {name: 'eye-icon', path: 'eye-icon.svg'},
	//   {name: 'lock-icon', path: 'lock-icon.svg'},
	//   {name: 'add-round-icon', path: 'add-round-icon.svg'},
	{name: 'options-icon', path: 'options-icon.svg'},
	{name: 'close-icon', path: 'close-icon.svg'}
	//   {name: 'upload-icon', path: 'upload-icon.svg'},
	//   {name: 'search-icon', path: 'search-icon.svg'},
	//   {name: 'show-details-icon', path: 'show-details-icon.svg'},
	//   {name: 'star-icon', path: 'star-icon.svg'},
	//   {name: 'info-icon', path: 'info-icon.svg'},
	//   {name: 'visa-icon', path: 'banking-cards-icons/visa-icon.svg'},
	//   {name: 'american-express-icon', path: 'banking-cards-icons/american-express-icon.svg'},
	//   {name: 'diners-club-icon', path: 'banking-cards-icons/diners-club-icon.svg'},
	//   {name: 'discover-icon', path: 'banking-cards-icons/discover-icon.svg'},
	//   {name: 'jcb-icon', path: 'banking-cards-icons/jcb-icon.svg'},
	//   {name: 'mastercard-icon', path: 'banking-cards-icons/mastercard-icon.svg'},
	//   {name: 'union-pay-icon', path: 'banking-cards-icons/union-pay-icon.svg'},
	//   {name: 'edit-icon', path: 'edit-icon.svg'},
	//   {name: 'blue-plus-icon', path: 'blue-plus-icon.svg'},
	//   {name: 'star-icon', path: 'star-icon.svg'},
	//   {name: 'transparent-star-icon', path: 'transparent-star-icon.svg'},
	//   {name: 'review-icon', path: 'profile-icons/review-icon.svg'},
	//   {name: 'verified-icon', path: 'profile-icons/verified-icon.svg'},
	//   {name: 'lock-icon', path: 'profile-icons/lock-icon.svg'},
	//   {name: 'education-icon', path: 'profile-icons/education-icon.svg'},
	//   {name: 'experience-icon', path: 'profile-icons/experience-icon.svg'},
	//   {name: 'journal-publication-icon', path: 'profile-icons/journal-publication-icon.svg'},
	//   {name: 'academic-research-icon', path: 'profile-icons/academic-research-icon.svg'},
	//   {name: 'business-icon', path: 'profile-icons/business-icon.svg'},
	//   {name: 'student-icon', path: 'profile-icons/student-icon.svg'},
	//   {name: 'individual-icon', path: 'profile-icons/individual-icon.svg'},
	//   {name: 'author-icon', path: 'profile-icons/author-icon.svg'},
	//   {name: 'medical-icon', path: 'profile-icons/medical-icon.svg'},
	//   {name: 'science-tech-icon', path: 'profile-icons/science-tech-icon.svg'},
	//   {name: 'business-subject-icon', path: 'profile-icons/business-subject-icon.svg'},
	//   {name: 'personal-icon', path: 'profile-icons/personal-icon.svg'},
	//   {name: 'social-sciences-icon', path: 'profile-icons/social-sciences-icon.svg'},
	//   {name: 'humanities-icon', path: 'profile-icons/humanities-icon.svg'},
	//   {name: 'media-arts-icon', path: 'profile-icons/media-arts-icon.svg'},
	//   {name: 'formats-icon', path: 'profile-icons/formats-icon.svg'},
	//   {name: 'reference-styles-icon', path: 'profile-icons/reference-styles-icon.svg'},
	//   {name: 'english-styles-icon', path: 'profile-icons/english-styles-icon.svg'},
	//   {name: 'baseline-price-icon', path: 'profile-icons/baseline-price-icon.svg'},
	//   {name: 'rush-delivery-icon', path: 'profile-icons/rush-delivery-icon.svg'},
	//   {name: 'additional-service-price-icon', path: 'profile-icons/additional-service-price-icon.svg'},
	//   {name: 'satisfaction-policies-icon', path: 'profile-icons/satisfaction-policies-icon.svg'},
	//   {name: 'arrow-left-icon', path: 'profile-icons/arrow-left-icon.svg'},
	//   {name: 'lock-round-icon', path: 'lock-round-icon.svg'},
	//   {name: 'basket-icon', path: 'basket-icon.svg'},
	//   {name: 'download-icon', path: 'download-icon.svg'},
	//   {name: 'calendar-icon', path: 'calendar-icon.svg'},
	//   {name: 'copy-icon', path: 'copy-icon.svg'},
	//   {name: 'send', path: 'send-button.svg'},
	//   {name: 'padlock', path: 'padlock.svg'},
	//   {name: 'complete-icon', path: 'complete-icon.svg'},
	//   {name: 'error-icon', path: 'error-icon.svg'}
];

export class IconRegistry {
	public static register(matIconRegistry: MatIconRegistry, domSanitizer: DomSanitizer): void {
		iconsConstant.forEach((icon): void => {
			matIconRegistry.addSvgIcon(icon.name, domSanitizer.bypassSecurityTrustResourceUrl(`assets/icons/${icon.path}`));
		});
	}
}
